# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Plivo SMS
      # You may pin to the exact commit or the version.
      # uses: huzaif-plivo/action-sms@d0f921598b8b159207c01c3282a79285bd2785b7
        uses: huzaif-plivo/action-sms@v1.0.0
        with:
          # Phone number in your Plivo account to send the SMS from
          fromPhoneNumber: "919900383513"
          # Phone number to send the SMS to
          toPhoneNumber: "918050897600"
          # The message you want to send
          message: "Hey, there!"
          # A Plivo auth_id. Can alternatively be stored in environment
          PLIVO_AUTH_ID: ${{ secrets.PLIVO_AUTH_ID }}
          # A Plivo auth_token. Can alternatively be stored in environment
          PLIVO_AUTH_TOKEN: ${{ secrets.PLIVO_AUTH_TOKEN }}
