# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  make-call:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.4
        id: hello
        uses: actions/setup-python@v2
        with:
          python-version: '3.4'        
        if: success()
      - name: Plivo Call
        uses: huzaif-plivo/action-call@v1.6
        with:
          fromPhoneNumber: ${{ secrets.FROM_NUMBER }}
          toPhoneNumber: ${{ secrets.TO_NUMBER }}
          message: steps.hello.outputs.status
          language: 'en-US'
          voice: 'MAN'
        env:
          PLIVO_AUTH_ID: ${{ secrets.PLIVO_AUTH_ID }}
          PLIVO_AUTH_TOKEN: ${{ secrets.PLIVO_AUTH_TOKEN }}
