# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Plivo SMS
        uses: huzaif-plivo/action-sms@2.0
        with:
          # Phone number in your Plivo account to send the SMS from
          fromPhoneNumber: ${{ secrets.FROM_NUMBER }}
          # Phone number to send the SMS to
          toPhoneNumber: ${{ secrets.TO_NUMBER }}
          # The message you want to send
          message: Hey, there!
        env:
          # A Plivo auth_id. Can alternatively be stored in environment
          PLIVO_AUTH_ID: ${{ secrets.PLIVO_AUTH_ID }}
          # A Plivo auth_token. Can alternatively be stored in environment
          PLIVO_AUTH_TOKEN: ${{ secrets.PLIVO_AUTH_TOKEN }}
